import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';
import '../../core/models/opportunity_model.dart';
import '../../core/providers/opportunity_provider.dart';
import '../../core/theme/app_colors.dart';
import 'package:firebase_auth/firebase_auth.dart' hide AuthProvider;
import '../../core/providers/auth_provider.dart';

class AddOpportunityScreen extends StatefulWidget {
  const AddOpportunityScreen({super.key});

  @override
  State<AddOpportunityScreen> createState() => _AddOpportunityScreenState();
}

class _AddOpportunityScreenState extends State<AddOpportunityScreen> {
  final _formKey = GlobalKey<FormState>();
  
  final _titleController = TextEditingController();
  final _companyController = TextEditingController();
  final _locationController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _externalLinkController = TextEditingController();
  
  String _selectedType = 'Emploi';
  final List<String> _types = ['Emploi', 'Stage', 'Freelance', 'Alternance', 'Bourse'];
  
  bool _isAdvancedOpen = false;
  bool _isLoading = false;

  void _submit() async {
    if (!_formKey.currentState!.validate()) return;
    
    setState(() => _isLoading = true);
    
    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user == null) throw Exception('Utilisateur non connecté');
      
      // BUSINESS RULE: Freemium B2B = 1 active opportunity limit. Premium = 50.
      final isPremium = context.read<AuthProvider>().userModel?.isPremium ?? false;
      final limit = isPremium ? 50 : 1;
      
      final currentOpsCount = context.read<OpportunityProvider>().opportunities
          .where((op) => op.postedBy == user.uid && op.status == 'open')
          .length;
          
      if (currentOpsCount >= limit) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Quota atteint. Limite Freemium: 1, Premium: 50. Vous avez $currentOpsCount offres actives.'),
              backgroundColor: Colors.red,
            ),
          );
          setState(() => _isLoading = false);
        }
        return;
      }

      final isExternal = _externalLinkController.text.trim().isNotEmpty;

      final newOpp = OpportunityModel(
        id: '', // Generated by Firestore
        title: _titleController.text.trim(),
        company: _companyController.text.trim(),
        location: _locationController.text.trim(),
        type: _selectedType,
        description: _descriptionController.text.trim(),
        postedBy: user.uid,
        createdAt: DateTime.now(),
        status: 'open', // UNIFIED STATUS: 'open'
        applicationType: isExternal ? 'external' : 'internal',
        externalLink: isExternal ? _externalLinkController.text.trim() : null,
      );

      await context.read<OpportunityProvider>().addOpportunity(newOpp);
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Opportunité publiée avec succès !'), backgroundColor: Colors.green),
        );
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Erreur: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _companyController.dispose();
    _locationController.dispose();
    _descriptionController.dispose();
    _externalLinkController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Créer une opportunité'),
        actions: [
          TextButton(
            onPressed: _isLoading ? null : _submit,
            child: _isLoading 
                ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2))
                : const Text('Publier', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(
                  labelText: 'Titre du poste *',
                  hintText: 'Ex: Développeur Flutter',
                ),
                validator: (v) => v!.isEmpty ? 'Ce champ est requis' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _companyController,
                decoration: const InputDecoration(
                  labelText: 'Nom de l\'entreprise *',
                  hintText: 'Ex: Kaïro',
                ),
                validator: (v) => v!.isEmpty ? 'Ce champ est requis' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _locationController,
                decoration: const InputDecoration(
                  labelText: 'Localisation *',
                  hintText: 'Ex: Ouagadougou ou Remote',
                ),
                validator: (v) => v!.isEmpty ? 'Ce champ est requis' : null,
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<String>(
                value: _selectedType,
                decoration: const InputDecoration(labelText: 'Type de contrat *'),
                items: _types.map((t) => DropdownMenuItem(value: t, child: Text(t))).toList(),
                onChanged: (v) => setState(() => _selectedType = v!),
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _descriptionController,
                maxLines: 8,
                decoration: const InputDecoration(
                  labelText: 'Description de l\'offre *',
                  hintText: 'Décrivez les missions, le profil recherché...',
                  alignLabelWithHint: true,
                ),
                validator: (v) => v!.isEmpty ? 'Ce champ est requis' : null,
              ),
              const SizedBox(height: 24),
              
              // Options avancées
              InkWell(
                onTap: () => setState(() => _isAdvancedOpen = !_isAdvancedOpen),
                child: Padding(
                  padding: const EdgeInsets.symmetric(vertical: 8),
                  child: Row(
                    children: [
                      Icon(_isAdvancedOpen ? PhosphorIcons.caretUp() : PhosphorIcons.caretDown()),
                      const SizedBox(width: 8),
                      const Text('Options avancées', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                    ],
                  ),
                ),
              ),
              if (_isAdvancedOpen) ...[
                const SizedBox(height: 16),
                TextFormField(
                  controller: _externalLinkController,
                  decoration: const InputDecoration(
                    labelText: 'Lien externe pour postuler (Optionnel)',
                    hintText: 'https://...',
                  ),
                ),
                const Padding(
                  padding: EdgeInsets.only(top: 8),
                  child: Text(
                    'Si renseigné, les candidats seront redirigés vers ce lien au lieu de postuler sur Kaïro.',
                    style: TextStyle(fontSize: 12, color: Colors.grey),
                  ),
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }
}
